"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
import os
from pathlib import Path

# Ensure we're on macOS
if sys.platform not in ('linux', 'darwin'):
    print("This setup script is for macOS only.")
    sys.exit(1)

# Fix for ruamel namespace package - create __init__.py if missing
# py2app uses imp.find_module which doesn't support PEP 420 namespace packages
import ruamel.yaml
ruamel_dir = os.path.dirname(os.path.dirname(ruamel.yaml.__file__))
ruamel_init = os.path.join(ruamel_dir, '__init__.py')
if not os.path.exists(ruamel_init):
    print(f"Creating temporary {ruamel_init} for py2app compatibility")
    with open(ruamel_init, 'w') as f:
        f.write("# Auto-generated for py2app compatibility\n")

APP = ['cwled.py']
APP_NAME = 'CWLed'

# Data files to include (resources directory)
DATA_FILES = [
    ('resources/config', [
        'resources/config/config.yaml',
        'resources/config/editor.yaml',
        'resources/config/dataStructures.yaml',
    ]),
    ('resources/icons', [
        str(p) for p in Path('resources/icons').glob('*.png')
    ] + [
        str(p) for p in Path('resources/icons').glob('*.icns')
    ]),
]

# Flatten icon files
icon_files = []
for p in Path('resources/icons').glob('*.png'):
    icon_files.append(str(p))
for p in Path('resources/icons').glob('*.icns'):
    icon_files.append(str(p))

DATA_FILES = [
    ('resources/config', [
        'resources/config/config.yaml',
    ]),
    ('resources/icons', icon_files),
]

# Add any additional config files that exist
config_files = ['resources/config/config.yaml']
for f in ['resources/config/editor.yaml', 'resources/config/dataStructures.yaml']:
    if os.path.exists(f):
        config_files.append(f)
DATA_FILES[0] = ('resources/config', config_files)

OPTIONS = {
    'argv_emulation': False,  # Set to False for better compatibility
    'iconfile': 'resources/icons/cwled.icns' if os.path.exists('resources/icons/cwled.icns') else None,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleIdentifier': 'com.cwled.cwleditor',
        'CFBundleVersion': '0.1a',
        'CFBundleShortVersionString': '0.1a',
        'NSHighResolutionCapable': True,
        'NSRequiresAquaSystemAppearance': False,  # Support dark mode
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName': 'CWL Document',
                'CFBundleTypeIconFile': 'cwled.icns',
                'CFBundleTypeExtensions': ['cwl'],
                'CFBundleTypeRole': 'Editor',
                'LSHandlerRank': 'Owner',
            },
            {
                'CFBundleTypeName': 'YAML Document',
                'CFBundleTypeExtensions': ['yaml', 'yml'],
                'CFBundleTypeRole': 'Editor',
                'LSHandlerRank': 'Alternate',
            },
            {
                'CFBundleTypeName': 'JSON Document',
                'CFBundleTypeExtensions': ['json'],
                'CFBundleTypeRole': 'Editor',
                'LSHandlerRank': 'Alternate',
            },
        ],
    },
    'packages': [
        'PyQt6',
        'PyQt6.Qsci',
        'ruamel',
        'ruamel.yaml',
        'cwl_utils',
        'schema_salad',
        'colorlog',
        'markdown2',
        'nested_lookup',
        'jinja2',
        'watchdog'
    ],
    'includes': [
        'cwled',
        'cwled.main',
        'cwled.MainWindow',
        'cwled.ChildWindow',
        'cwled.CWLparser',
        'cwled.configuration',
        'cwled.data',
    ],
    'excludes': [
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'PySide6',
        'shiboken6',
        'PyQt5',
        'PySide2',
    ],
    'resources': [
        'resources',
    ],
}

# Remove None iconfile if it doesn't exist
if OPTIONS['iconfile'] is None:
    del OPTIONS['iconfile']

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
